import Link from "next/link";

export default function Home() {
  return <main className="landing">
    <header className="landing-nav"><p>Bridge<span>TheGap</span></p><nav><a href="#workflow">Lifecycle</a><a href="#proof">Evidence</a><Link href="/workspace">Log in</Link><Link className="landing-cta" href="/workspace">Open workspace</Link></nav></header>
    <section className="landing-hero"><div><p className="eyebrow">Gujarat R&B bridge lifecycle platform</p><h1>Every bridge.<br />Every decision.<br /><em>One accountable record.</em></h1><p className="landing-copy">A bridge-first operational system that connects sanction, clearance, tendering, construction evidence, inspection, rectification, and verified closure.</p><div className="landing-actions"><Link className="landing-cta" href="/workspace">Start the live demo</Link><a className="landing-secondary" href="#workflow">See the lifecycle</a></div><div className="landing-proof"><span>● Permanent asset passport</span><span>● Role-based controls</span><span>● Evidence-led audit trail</span></div></div><div className="bridge-mark" aria-label="Abstract bridge lifecycle visual"><i /><i /><i /><i /><i /><i /><b>01</b></div></section>
    <section id="workflow" className="landing-flow"><p className="eyebrow">From need to verified closure</p><div>{[["01","Sanction & clearance","PFR / FSR / DPR, approvals and project-specific clearances."],["02","Tender & execution","Controlled tender room, contract, tests and quality evidence."],["03","Operations & maintenance","Inspection, ATR, repair, independent verification and audit." ]].map(([number,title,copy]) => <article key={number}><strong>{number}</strong><h2>{title}</h2><p>{copy}</p></article>)}</div></section>
    <section id="proof" className="landing-statement"><p className="eyebrow">Not another asset spreadsheet</p><h2>A failed clearance, test or repair cannot disappear into a disconnected file.</h2><Link className="landing-cta" href="/workspace">Enter the operations workspace</Link></section>
  </main>;
}
