"use client";

import { useEffect, useState } from "react";

const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
type Project = { id: string; name: string; division: string; estimate: number; status: string };
type Bridge = { id: string; name: string; code: string; service_status: string; maintenance_status: string; next_inspection: string };
type Summary = { projects: number; bridges: number; attention_required: number; active_work_orders: number };

const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });

export default function Home() {
  const [view, setView] = useState("Overview");
  const [summary, setSummary] = useState<Summary | null>(null);
  const [projects, setProjects] = useState<Project[]>([]);
  const [bridges, setBridges] = useState<Bridge[]>([]);
  const [notice, setNotice] = useState("Connecting to the lifecycle API…");

  const load = async () => {
    try {
      const [dashboard, projectList, bridgeList] = await Promise.all([fetch(`${api}/api/dashboard/summary`), fetch(`${api}/api/projects`), fetch(`${api}/api/bridges`)]);
      if (![dashboard, projectList, bridgeList].every((response) => response.ok)) throw new Error();
      setSummary(await dashboard.json()); setProjects(await projectList.json()); setBridges(await bridgeList.json()); setNotice("Live demo data loaded from Render.");
    } catch { setNotice("API unavailable. Check NEXT_PUBLIC_API_URL and the Render service."); }
  };
  useEffect(() => {
    const timer = window.setTimeout(() => { void load(); }, 0);
    return () => window.clearTimeout(timer);
  }, []);

  const award = async () => { const response = await fetch(`${api}/api/tenders/TEN-001/award`, { method: "POST" }); setNotice(response.ok ? "Tender awarded and contract record created." : "Award could not be recorded."); await load(); };
  const inspect = async () => { const response = await fetch(`${api}/api/bridges/BRG-001/inspections`, { method: "POST" }); setNotice(response.ok ? "Inspection submitted. Engineering disposition is now required." : "Inspection could not be submitted."); await load(); };

  return <main className="min-h-screen bg-[#07111f] text-slate-100"><div className="mx-auto grid min-h-screen max-w-[1500px] lg:grid-cols-[248px_1fr]"><aside className="border-b border-slate-800 bg-[#0a1627] p-6 lg:border-b-0 lg:border-r"><p className="text-xs font-bold tracking-[.22em] text-cyan-300">GUJARAT R&B · DEMO</p><h1 className="mt-2 text-2xl font-semibold">BridgeTheGap</h1><p className="mt-2 text-sm text-slate-400">Lifecycle operations workspace</p><nav className="mt-10 space-y-2">{["Overview", "Projects & tenders", "Construction", "Bridge assets", "Work queue"].map((item) => <button key={item} onClick={() => setView(item)} className={`w-full rounded-lg px-3 py-2.5 text-left text-sm transition ${view === item ? "bg-cyan-300 text-slate-950 font-semibold" : "text-slate-300 hover:bg-slate-800"}`}>{item}</button>)}</nav><div className="mt-10 rounded-xl border border-slate-700 bg-slate-900/60 p-4 text-xs text-slate-400"><p className="font-semibold text-slate-200">Prototype policy</p><p className="mt-2">All records are fictional. No compliance, safety, GIS, payment, or live-government claim is made.</p></div></aside><section className="p-6 md:p-10"><header className="flex flex-col gap-4 border-b border-slate-800 pb-6 md:flex-row md:items-center md:justify-between"><div><p className="text-sm text-cyan-300">{view}</p><h2 className="mt-1 text-3xl font-semibold">Decision-ready lifecycle management</h2></div><button onClick={() => void load()} className="rounded-lg border border-slate-700 px-4 py-2 text-sm font-semibold hover:border-cyan-300">Refresh data</button></header><p className="mt-5 rounded-lg border border-slate-800 bg-slate-900/70 px-4 py-3 text-sm text-slate-300">{notice}</p>{view === "Overview" && <Overview summary={summary} projects={projects} bridges={bridges} onAward={award} onInspect={inspect}/>} {view === "Projects & tenders" && <Projects projects={projects} onAward={award}/>} {view === "Construction" && <Construction/>} {view === "Bridge assets" && <Assets bridges={bridges} onInspect={inspect}/>} {view === "Work queue" && <WorkQueue bridges={bridges}/>}</section></div></main>;
}

function Overview({ summary, projects, bridges, onAward, onInspect }: { summary: Summary | null; projects: Project[]; bridges: Bridge[]; onAward: () => void; onInspect: () => void }) { const cards = [["Projects", summary?.projects], ["Bridge assets", summary?.bridges], ["Disposition required", summary?.attention_required], ["Active work", summary?.active_work_orders]]; return <><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <article key={String(label)} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-3xl font-semibold text-cyan-200">{value ?? "—"}</p></article>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-2"><Panel title="Project pipeline"><ProjectTable projects={projects}/><button onClick={onAward} className="mt-5 rounded-lg bg-cyan-300 px-4 py-2 text-sm font-semibold text-slate-950">Record tender award</button></Panel><Panel title="Attention queue">{bridges.map((bridge) => <div key={bridge.id} className="rounded-lg border border-amber-300/20 bg-amber-300/5 p-4"><p className="font-semibold">{bridge.name}</p><p className="mt-1 text-sm text-amber-100">{bridge.maintenance_status === "ACTION_REQUIRED" ? "Inspection needs an engineering disposition." : "Submit a demo inspection to test escalation."}</p><button onClick={onInspect} className="mt-3 text-sm font-semibold text-cyan-200">Submit inspection →</button></div>)}</Panel></div></> }
function Projects({ projects, onAward }: { projects: Project[]; onAward: () => void }) { return <div className="mt-8"><Panel title="Tender and award register"><ProjectTable projects={projects}/><div className="mt-6 rounded-lg bg-slate-800 p-4 text-sm text-slate-300">Seeded bids: Saffron Infrastructure — ₹1.185 Cr · Narmada Works — ₹1.210 Cr</div><button onClick={onAward} className="mt-4 rounded-lg bg-cyan-300 px-4 py-2 font-semibold text-slate-950">Award lowest submitted bid</button></Panel></div> }
function Construction() { return <div className="mt-8 grid gap-4 md:grid-cols-3">{[["Site mobilisation", "Not started"], ["Quality checkpoint", "Awaiting contractor"], ["Handover", "Blocked until completion"]].map(([title, state]) => <article key={title} className="rounded-xl border border-slate-800 bg-slate-900 p-6"><p className="text-sm text-slate-400">{title}</p><p className="mt-3 font-semibold text-cyan-200">{state}</p><p className="mt-5 text-sm text-slate-400">Construction controls are represented as accountable milestones, not fabricated laboratory records.</p></article>)}</div> }
function Assets({ bridges, onInspect }: { bridges: Bridge[]; onInspect: () => void }) { return <div className="mt-8"><Panel title="Bridge asset passport"><div className="space-y-4">{bridges.map((bridge) => <div key={bridge.id} className="flex flex-col justify-between gap-4 rounded-lg border border-slate-800 p-5 md:flex-row"><div><p className="font-semibold">{bridge.name}</p><p className="mt-1 text-sm text-slate-400">{bridge.code} · Next inspection {bridge.next_inspection}</p></div><div className="flex items-center gap-3"><span className="rounded-full bg-emerald-300/10 px-3 py-1 text-xs text-emerald-100">{bridge.service_status}</span><button onClick={onInspect} className="rounded-lg border border-cyan-400/50 px-3 py-2 text-sm text-cyan-200">Submit inspection</button></div></div>)}</div></Panel></div> }
function WorkQueue({ bridges }: { bridges: Bridge[] }) { return <div className="mt-8"><Panel title="Open intervention queue">{bridges.map((bridge) => <div key={bridge.id} className="rounded-lg bg-slate-800 p-5"><p className="font-semibold">{bridge.name}</p><p className="mt-2 text-sm text-slate-400">Current maintenance state: {bridge.maintenance_status}</p><p className="mt-4 text-sm text-cyan-200">Engineer decision → contractor completion → independent verification</p></div>)}</Panel></div> }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h3 className="text-lg font-semibold">{title}</h3><div className="mt-5">{children}</div></section> }
function ProjectTable({ projects }: { projects: Project[] }) { return <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-400"><tr><th className="pb-3">Project</th><th className="pb-3">Division</th><th className="pb-3">Estimate</th><th className="pb-3">Stage</th></tr></thead><tbody>{projects.map((project) => <tr key={project.id} className="border-t border-slate-800"><td className="py-3 font-medium">{project.name}</td><td>{project.division}</td><td>{money.format(project.estimate)}</td><td><span className="rounded-full bg-amber-300/10 px-2 py-1 text-xs text-amber-100">{project.status.replaceAll("_", " ")}</span></td></tr>)}</tbody></table></div> }
