"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Summary = { projects: number; bridges: number; attention_required: number; active_work_orders: number };
const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";

export default function Workspace() {
  const [summary, setSummary] = useState<Summary | null>(null);
  const [message, setMessage] = useState("Loading live lifecycle data…");
  useEffect(() => { fetch(`${api}/api/dashboard/summary`).then((r) => r.ok ? r.json() : Promise.reject()).then((data) => { setSummary(data); setMessage("Connected to the deployed lifecycle API."); }).catch(() => setMessage("The API is unavailable. Check the Render service and Vercel environment variable.")); }, []);
  const cards = [["Active projects", summary?.projects], ["Bridge assets", summary?.bridges], ["Disposition required", summary?.attention_required], ["Active work orders", summary?.active_work_orders]];
  return <main className="min-h-screen bg-[#07111f] p-6 text-slate-100 md:p-10"><header className="mx-auto flex max-w-7xl items-center justify-between border-b border-slate-800 pb-6"><div><Link href="/" className="text-sm text-cyan-200">← Landing page</Link><h1 className="mt-3 text-3xl font-semibold">Lifecycle command centre</h1></div><span className="rounded-full border border-cyan-300/40 px-3 py-1 text-xs text-cyan-100">Fictional demo data</span></header><p className="mx-auto mt-6 max-w-7xl rounded-lg bg-slate-900 p-4 text-sm text-slate-300">{message}</p><section className="mx-auto mt-6 grid max-w-7xl gap-4 md:grid-cols-4">{cards.map(([label, value]) => <article key={String(label)} className="rounded-xl border border-slate-800 bg-slate-900 p-5"><p className="text-sm text-slate-400">{label}</p><p className="mt-3 text-3xl font-semibold text-cyan-200">{value ?? "—"}</p></article>)}</section><section className="mx-auto mt-6 grid max-w-7xl gap-6 lg:grid-cols-2"><article className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Mahi River Bridge Rehabilitation</h2><p className="mt-2 text-slate-400">Vadodara Division · PRJ-001 · Tender evaluation in progress</p><ol className="mt-6 space-y-3">{["Need identified", "Administrative approval", "Technical sanction", "Tender open", "Award", "Construction", "Handover", "In service"].map((item, index) => <li key={item} className={`flex items-center gap-3 ${index <= 3 ? "text-cyan-100" : "text-slate-500"}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full text-xs ${index <= 3 ? "bg-cyan-300 text-slate-950" : "bg-slate-800"}`}>{index + 1}</span>{item}</li>)}</ol></article><article className="rounded-xl border border-slate-800 bg-slate-900 p-6"><h2 className="text-xl font-semibold">Accountability queue</h2><div className="mt-5 rounded-lg bg-amber-300/10 p-4 text-amber-100"><p className="font-semibold">GJ-RB-042 · Mahi River Bridge</p><p className="mt-2 text-sm">Inspection finding requires an Executive Engineer disposition before closure.</p></div><div className="mt-5 rounded-lg bg-slate-800 p-4 text-sm"><p className="font-semibold">Evidence boundary</p><p className="mt-2 text-slate-400">This workflow records decisions and audit events. It does not automate structural safety or make official compliance claims.</p></div></article></section></main>;
}
